name: Common

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      username:
        required: true
      password:
        required: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Publish
      uses: elgohr/Publish-Docker-Github-Action@main
      with:
        name: shish2k/rosettaboy-devkit-${{ inputs.language }}
        dockerfile: ${{ inputs.language }}.dockerfile
        buildoptions: "--build-arg VERSION=${{ inputs.version }}"
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        tags: ${{ inputs.version }}
        platforms: linux/amd64,linux/arm64
    - name: Update Badge
      uses: RubbaBoy/BYOB@v1.3.0
      with:
        NAME: ${{ inputs.language }}-version
        LABEL: ${{ inputs.language }}
        STATUS: ${{ inputs.version }}
        COLOR: 1C8F11
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
