name: Common

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      version:
        required: true
        type: string
    secrets:
      username:
        required: true
        type: string
      password:
        required: true
        type: string

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Publish
      uses: elgohr/Publish-Docker-Github-Action@main
      with:
        name: shish2k/rosettaboy-devkit-${{ inputs.language }}
        dockerfile: ${{ inputs.language }}.dockerfile
        buildoptions: "--build-arg VERSION=${{ inputs.version }}"
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        tags: ${{ inputs.version }}
        platforms: linux/amd64,linux/arm64
