name: go

on:
  workflow_dispatch:

jobs:
  build:
    name: Common
    uses: ./.github/workflows/_common.yml
    with:
      language: go
      version: 1.22.2
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
