name: go

on:
  workflow_dispatch:

jobs:
  build:
    name: go
    uses: ./.github/workflows/_common_deb.yml
    permissions:
      contents: write
    with:
      language: go
      version: 1.24.3
      build: |
        wget -qO- https://go.dev/dl/go${VERSION}.linux-${DEB_BUILD_GNU_CPU}.tar.gz \
          | tar --strip-components=1 -xz --one-top-level=pkg/opt/go
