name: nim

on:
  workflow_dispatch:

jobs:
  build:
    name: nim
    uses: ./.github/workflows/_common_deb.yml
    permissions:
      contents: write
    with:
      language: nim
      version: 2.2.4
      build: |
        wget -qO- https://nim-lang.org/download/nim-${VERSION}.tar.xz \
          | tar --strip-components=1 -xJ --one-top-level=src
        cd src
        ./build.sh
        bin/nim c koch
        ./koch boot -d:release
        ./koch tools
        ./install.sh /tmp/install-nim
        mkdir -p ../pkg/opt/nim
        mv /tmp/install-nim/nim/* ../pkg/opt/nim
        cp ./bin/nimble ../pkg/opt/nim/bin/
