name: nim

on:
  workflow_dispatch:

jobs:
  build:
    name: Common
    uses: ./.github/workflows/_common.yml
    permissions:
      contents: write
    with:
      language: nim
      version: 2.2.4
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
