name: ocaml

on:
  workflow_dispatch:

jobs:
  build:
    name: Common
    uses: ./.github/workflows/_common.yml
    permissions:
      contents: write
    with:
      language: ocaml
      version: 5.1.1
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
