name: php

on:
  workflow_dispatch:

jobs:
  build:
    name: Common
    uses: ./.github/workflows/_common.yml
    permissions:
      contents: write
    with:
      language: php
      version: 8.4.6
    secrets:
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}
