name: zig

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.app }} ${{ matrix.version }} ${{ matrix.os }}
    uses: ./.github/workflows/_common_deb.yml
    permissions:
      contents: write
    strategy:
      matrix:
        version: [0.14.1]
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    with:
      language: zig
      version: ${{ matrix.version }}
      os: ${{ matrix.os }}
      build: |
        wget --quiet -O - https://ziglang.org/download/${{ matrix.version }}/zig-$(dpkg-architecture -q DEB_BUILD_GNU_CPU)-linux-${{ matrix.version }}.tar.xz | \
            tar xJf - --one-top-level=src --strip-components=1
        mkdir -p pkg/usr/bin pkg/usr/lib
        mv src/lib pkg/usr/lib/zig
        mv src/zig pkg/usr/bin/zig
