name: zig

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.app }} ${{ matrix.version }} ${{ matrix.os }}
    #permissions:
    #  contents: write  # to update badges
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        app: [zig]
        version: [0.14.1]
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    steps:
      - name: Set vars
        run: |
          echo "DATETIME=$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
          dpkg-architecture >> $GITHUB_ENV

      - name: Build app
        run: |
          mkdir -p pkg/usr/bin pkg/usr/lib pkg/DEBIAN
          wget -O - https://ziglang.org/download/${{ matrix.version }}/zig-${{ env.DEB_BUILD_GNU_CPU }}-linux-${{ matrix.version }}.tar.xz | \
              tar --one-top-level=unpack --strip-components=1 xJf -
          mv unpack/lib pkg/usr/lib/zig
          mv unpack/zig pkg/usr/bin/zig
          echo "Package: ${{ matrix.app }}" > pkg/DEBIAN/control
          echo "Version: ${{ matrix.version }}.${{ env.DATETIME }}" >> pkg/DEBIAN/control
          echo "Architecture: ${{ env.DEB_BUILD_ARCH }}" >> pkg/DEBIAN/control
          echo "Maintainer: Shish <shish@shishnet.org>" >> pkg/DEBIAN/control
          dpkg-deb --build pkg ${{ matrix.app }}.deb

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.app }}-${{ matrix.version }}.${{ env.DATETIME }}-${{ env.DEB_BUILD_ARCH }}.deb
          path: ${{ matrix.app }}.deb
          #retention-days: 5
#      - name: Update Badge
#        uses: RubbaBoy/BYOB@v1.3.0
#        with:
#          NAME: ${{ matrix.app }}-version
#          LABEL: ${{ matrix.app }}
#          STATUS: ${{ matrix.version }}
#          COLOR: 1C8F11
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
