name: zig

on:
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.app }} ${{ matrix.version }} ${{ matrix.os }}
    permissions:
      contents: write # to update releases
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        app: [zig]
        version: [0.14.1]
        os: [ubuntu-24.04, ubuntu-24.04-arm]
    steps:
      - name: Set vars
        run: |
          export DATETIME=$(date +'%Y%m%d.%H%M%S')
          echo "DATETIME=$DATETIME" >> $GITHUB_ENV
          export $(dpkg-architecture)
          dpkg-architecture >> $GITHUB_ENV
          echo "PKG=rosettaboy-${{ matrix.app }}-dev" >> $GITHUB_ENV
          echo "PKG_FILE=rosettaboy-${{ matrix.app }}-dev_${{ matrix.version }}.${DATETIME}_${DEB_BUILD_ARCH}.deb" >> $GITHUB_ENV

      - name: Build app
        run: |
          wget --quiet -O - https://ziglang.org/download/${{ matrix.version }}/zig-${{ env.DEB_BUILD_GNU_CPU }}-linux-${{ matrix.version }}.tar.xz | \
              tar xJf - --one-top-level=src --strip-components=1
          mkdir -p pkg/usr/bin pkg/usr/lib
          mv src/lib pkg/usr/lib/zig
          mv src/zig pkg/usr/bin/zig

      - name: Build package
        run: |
          mkdir -p pkg/DEBIAN
          echo "Package: ${{ env.PKG }}" > pkg/DEBIAN/control
          echo "Version: ${{ matrix.version }}.${{ env.DATETIME }}" >> pkg/DEBIAN/control
          echo "Description: Rosettaboy Devkit" >> pkg/DEBIAN/control
          echo "Architecture: ${{ env.DEB_BUILD_ARCH }}" >> pkg/DEBIAN/control
          echo "Maintainer: Shish <shish@shishnet.org>" >> pkg/DEBIAN/control
          dpkg-deb --build pkg ${{ env.PKG_FILE }}

      - name: Upload package
        uses: svenstaro/upload-release-action@v2
        with:
          file: ${{ env.PKG_FILE }}
          tag: nightly
#      - name: Upload package
#        uses: actions/upload-artifact@v4
#        with:
#          name: ${{ env.PKG_FILE }}
#          path: ${{ env.PKG_FILE }}
#          #retention-days: 5
#      - name: Update Badge
#        uses: RubbaBoy/BYOB@v1.3.0
#        with:
#          NAME: ${{ matrix.app }}-version
#          LABEL: ${{ matrix.app }}
#          STATUS: ${{ matrix.version }}
#          COLOR: 1C8F11
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
