name: zig

on:
  workflow_dispatch:

jobs:
  build:
    name: zig
    uses: ./.github/workflows/_common_deb.yml
    permissions:
      contents: write
    with:
      language: zig
      version: 0.14.1
      build: |
        wget --quiet -O - https://ziglang.org/download/${VERSION}/zig-${DEB_BUILD_GNU_CPU}-linux-${VERSION}.tar.xz | \
            tar xJf - --one-top-level=src --strip-components=1
        mkdir -p pkg/usr/bin pkg/usr/lib
        mv src/lib pkg/usr/lib/zig
        mv src/zig pkg/usr/bin/zig
